modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Zombie%20Horse%20Spawn"

[[mods]]
modId="zombiehorsespawn"
version="2.7"
displayName="Zombie Horse Spawn"
displayURL="https://curseforge.com/minecraft/mc-mods/zombie-horse-spawn"
authors="Rick South"
description="Allows the zombie horse to spawn with a zombie riding it and other tweaks."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Alister, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.zombiehorsespawn]]
    modId="collective"
    mandatory=true
    versionRange="[2.20,)"
    ordering="NONE"
    side="BOTH"