modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Naturally%20Charged%20Creepers"

[[mods]]
modId="naturallychargedcreepers"
version="1.4"
displayName="Naturally Charged Creepers"
displayURL="https://curseforge.com/minecraft/mc-mods/naturally-charged-creepers"
authors="Rick South"
description="A minimalistic mod that allows creepers to spawn charged, both naturally and from a spawn egg."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.naturallychargedcreepers]]
    modId="collective"
    mandatory=true
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"