modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Stray%20Spawn"

[[mods]]
modId="strayspawn"
version="1.3"
displayName="Stray Spawn"
displayURL="https://curseforge.com/minecraft/mc-mods/stray-spawn"
authors="Rick South"
description="Allows a chance for strays to spawn naturally everywhere instead of a skeleton."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Alister, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.strayspawn]]
    modId="collective"
    mandatory=true
    versionRange="[2.24,)"
    ordering="NONE"
    side="BOTH"